### ISSUE TITLE
String Split function needs to be added in the setQueueForDataItem method in fifo.c

### ISSUE THREAD

**Issue by m4n1c22** [m4n1c22/os_labs#7]
Kindly add a bug free and memory leak free code for performing the string split function.
The input to function will be string of the form : "1, 1124352, helloworld"
1: corresponds to qid,
1124352: corresponds to the time
helloworld corresponds to the msg
kindly parse this information from the provided string and populate the struct data_item and store in the queue. 

_Note_:_strtok()_ and _strsep()_ can be inspiring but they have code re-entrant problems. Kindly don't use them inside the kernel implementation because they can cause problems. Hope you have fun!!!

**Comment by m4n1c22** [comment]
I would recommend you to implement  a split functionality on your own rather than using the standard string functions.

**Comment by pradeepb6** [comment]
Bug is fixed

**Comment by m4n1c22** [comment]
Code is still buggy and throws unwanted values or you can say garbage values. Kindly look into.

**Comment by m4n1c22** [comment]
Requirements changed. Not more an issue..
